### ISSUE TITLE
Problem with correction transmission through BT

### ISSUE THREAD

**Issue by Eric-FR** [sparkfun/SparkFun_RTK_Firmware#359]
RTK Express

Connected to Android smartphone with BT using whatever Lefebure TRIP, BT_GNSS os SW_Maps.

I discovered that age of differential was unstable and was quite often increasing until the limit of 60 s, loosing RTK correction. Looking at previous records, this is new (fall 22).

Last July:
$GNTXT,01,01,03,v2.2-Jun  8 2022*6C
$GNTXT,01,01,04,HPG 1.30*36

![image](https://user-images.githubusercontent.com/32433543/200135558-aa4467b8-67ae-4390-8477-b727a7c662e5.png)

Last month:
$GNTXT,01,01,03,v2.6-Sep 30 2022*64
$GNTXT,01,01,04,HPG 1.32*34

Same setup, same road at the beginning.

![image](https://user-images.githubusercontent.com/32433543/200135763-24dc6cd2-c283-4f19-aa9c-9ba64ce7f360.png)

Looking at other files, the problem should have started with:
$GNTXT,01,01,03,v2.5-Sep 21 2022*67
$GNTXT,01,01,04,HPG 1.32*34

In Lefebure, one can clear see that Lefebure is well receiving correction data.

I made a cross check with my home made logger that is also using BT for corrections. It doesn't suffer from such lags.

**Comment by Eric-FR** [comment]
Typically, what I observed with Lefebure (antenna on top of the car without moving, in urban area with good GNSS and 4G reception):

![photo_2022-11-03_13-44-26](https://user-images.githubusercontent.com/32433543/200136872-209614bb-d299-44a0-98a9-20745e864241.jpg)
![photo_2022-11-03_13-44-39](https://user-images.githubusercontent.com/32433543/200136874-aa17c80f-a8c7-4997-b3ac-48dfd918c3bc.jpg)
![photo_2022-11-03_13-44-51](https://user-images.githubusercontent.com/32433543/200136875-0288a79b-b31a-40d0-a549-5a8b83907ecf.jpg)
![photo_2022-11-03_13-44-58](https://user-images.githubusercontent.com/32433543/200136876-c2f60342-b1eb-4488-9d79-fded55883d79.jpg)

**Comment by nseidle** [comment]
@Eric-FR - Thank you for reporting! My apologies for the delay. 

I have attempted to replicate this issue and I'm not yet able to. Below is a capture to replicate your ~200k of data received and RTK lost.

![image](https://user-images.githubusercontent.com/117102/222561254-23880698-2a57-47f4-b8d5-05e23578ce77.png)

I'm able to have both solid reception within Lefebure and on the unit (RTK fix the entire time). I am not driving anywhere but if driving affects the reception of NTRIP corrections, there's nothing really that we can do.

My tests were done with v3.1 firmware. I could go back in time to further try to replicate the issue when you reported it on v2.6 but since it's working now, I'm hesitant to do so.

I'm going to close this as solved for now. Please let me know if you see anything like this again and we'll keep digging.
