### ISSUE TITLE
Display shows 1.04m "accuracy" and 0 satellites

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Firmware#400]
UPDATE:  Reboot cleared the discrepency.

###Observed behavior:
Zero satellites.
1.0 meter accuracy.
Dish antenna is blinking. 
Single crosshairs are solidly on. 

How can this be?  

f/w 3.1

![image](https://user-images.githubusercontent.com/17495167/218332791-05185655-ef91-4143-8e90-08112d08c802.jpeg)

**Comment by tonycanike** [comment]
A reboot sorted it all out.   I'm not terribly worried about it, just thought I'd report it.

**Comment by nseidle** [comment]
Ya, I've seen it too. It's very difficult to recreate. Thanks for reporting the Firmware version as we've been trying to mitigate it over the versions but obviously it's still lurking.

**Comment by nseidle** [comment]
I *think* this was related to #455. There was a bug in the GNSS library that may have been preventing PMP, PVT, and other messages from being transferred correctly. This was fixed [here](https://github.com/sparkfun/SparkFun_u-blox_GNSS_v3/commit/c1c857b2c374027ab664870b1f11afe98968d446) in the GNSS library. This fix was not in RTK firmware version v3.2 and below.

I'm going to mark this 'fixed' because I believe this was the culprit, and haven't seen this bug occur again for a long time, but let me know if it pops up again.

**Comment by nseidle** [comment]
This should be fixed in [v3.3 of the RTK firmware](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v.3.3). Please let us know if you still see problems.
