### ISSUE TITLE
Facet does not power up

### ISSUE THREAD

**Issue by caradag** [sparkfun/SparkFun_RTK_Firmware#750]
### Subject of the issue
Some facts:
- A Sparkfun Facet does not power up (after a couple of years of normal operation).
- When connected to power, the green light turns on and turns off once charged (as normal).
- When pressing the power-up button, nothing happens; it does not turn on.
- After opening the case I could check that the batteries are fully charged (4.15 v)
- With the case open, I can see that an orange LED turns on in the board containing the ESP and Ublox chips. This happens when I press the power button, but after a couple of seconds it turns off again and nothing else happens. I see the same behaviour even given if I keep the button pressed for several seconds.
- I tried pressing the pushbutton on the inside of the casing just on the other side of the PCB with the power button and the behaviour is the same as with the external button.
- Other, perhaps unrelated fact, is that before it started to refuse tu turn on. When off and connected to power, the Sparkfun logo was coming and going in the screen. As if the device was resetting every few seconds (I have a video of that if useful). 
-
### Your workbench
* firmware version 3.9
* What radios are you using?: None

**Comment by nseidle** [comment]
Hi - Sorry I missed this! Based on the age of the device, I suspect it has an accelerometer inside. This has led to various problems including a failed display. I recommend replacing the display board.

Because your device is (likely) out of warranty, I recommend having a look at the [Repair docs](https://docs.sparkfun.com/SparkFun_RTK_Firmware/repair/) and order a new [display kit](https://www.sparkfun.com/products/24705). 

This repo is generally for bugs in the firmware and less about hardware issues. If you run into hardware issues, [the forum](https://forum.sparkfun.com/viewforum.php?f=116) is really the best place to get help.
