### ISSUE TITLE
Debug Mode - Display GPS Location/Status

### ISSUE THREAD

**Issue by LeeLeahy2** [sparkfun/SparkFun_RTK_Firmware#82]
### Display GPS Location and Status via Serial
Please add an entry to the serial debug menu to display the GPS location and status
* Longitude
* Latitude
* Altitude
* Accuracy
* Satellite Count
* Locked
* State
* etc.

### Use Case
* RTK Express used as a remote base station connected through serial to another networked computer (PC, Raspberry Pi, ESP32, etc.).  Enable remote access to  GPS location and status via serial.

**Comment by LeeLeahy2** [comment]
Hi Nathan - I like the header to the debug menu with longitude and latitude.  My original thought was to add an item to the debug menu, say #9, 'g'  or 's'.  The the menu item could display one or more lines duplicating what is available on the display:
* GPS locked or searching
* Resolution?  e.g. 1.5 m
* Survey In mode / versus locked
* Number of satellites
* Battery level
* MAC address
* etc.
Personally, I would move the Ellipsoid, Mean Sea Level and Accuracy into the debug menu item, mainly because I don't understand these values yet.  For the single line, I would display Altitude above mean sea level, and point or survey accuracy (the value on the front panel, smaller is better).

**Comment by nseidle** [comment]
> Resolution? e.g. 1.5 m

I think you mean horizontal positional accuracy. This is the number on the screen and is captured by 'Accuracy' above.

> MAC address

It's easy enough and I don't mean to be rude, but why do you need this? For your reference, the last four digits of the Bluetooth MAC address are shown at the top of the main menu:

![image](https://user-images.githubusercontent.com/117102/158267047-2fa1f07d-e9c7-4bc4-816b-ee690445b89c.png)

I get you want to remote access to the system status over serial. Rather than trying to parse each of these bits from various spots, why don't we elect a special character (~ for example) that once received, causes the system to output all its stats via comma delimited string. For example we could do:

    $GNTXT,data/time,mac,lat,log,hpa,system state,batt level, ... *4B (CRC)

A very long sentence. It would be terminated with a CRC so yes, it's a NMEA sentence, but this would allow you to write a simple parser.

**Comment by LeeLeahy2** [comment]
HI Nathan,

If in your example ~ would toggle the output on and off, that would be
great.  Let me confirm that this would be output via the Config ESP32 port.

I was originally thinking that this output would be a one shot, print it
and done.  However, your suggestion would allow the computer to parse and
display this data on a regular basis and effectively duplicate the RTK
Express display.  That sounds great.

**Comment by nseidle** [comment]
This is coming along nicely. Is this output helpful?

`01,01,05,` are header bytes.

![image](https://user-images.githubusercontent.com/117102/160967454-53142651-7a52-44fe-8bab-51f391b0dcac.png)

        char systemStatus[100];
        sprintf(systemStatus, "%02d%02d%02d.%02d,%02d%02d%02d,%0.3f,%d,%0.9f,%0.9f,%0.2f,%d,%d,%d",
                hour, minute, second, mseconds,
                day, month, year,
                f_accuracy, siv,
                d_lat, d_lon,
                f_msl,
                fixType, rtkSolution,
                battLevel
                );

Hello from a mile above sea level!

**Comment by nseidle** [comment]
This technically violates the maximum length of [82 characters](https://github.com/sparkfun/SparkFun_RTK_Firmware/issues/74#issuecomment-1003091283) for a NMEA sentence but since this isn't being recorded to a log file, we should be ok.

**Comment by nseidle** [comment]
The ~ command has been implemented in RCApr1 and beyond. Please give it a try and let me know if there is other information that should be contained in the message.

**Comment by nseidle** [comment]
Featured added and rolled into v1.11 release.

**Comment by LeeLeahy2** [comment]
Hi Nathan,

This looks good.  My only suggestion would be to display year, month and
day before the hour minute...  As a single value it is
monotonically increasing until 2300.

Lee Leahy
(808) 692-3394
